import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          
      <body className={inter.className} >
        <Theme>{children}</Theme>
        <p className='text-center mb-8'>
          <a className='no-underline text-black uppercase' href='https://www.musaamuhsen.co.uk/'  target="_blank" 
            rel="noopener noreferrer">musaamuhsen.co.uk</a> &copy; 2024</p>
      </body>
    </html>
  );
}
